// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/definitions/definitions.proto

package definitions

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	LastUpdate           int32    `protobuf:"varint,3,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	Expiration           int32    `protobuf:"varint,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Item) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Item) GetLastUpdate() int32 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *Item) GetExpiration() int32 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type AddRequest struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type CompareAndSwapRequest struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompareAndSwapRequest) Reset()         { *m = CompareAndSwapRequest{} }
func (m *CompareAndSwapRequest) String() string { return proto.CompactTextString(m) }
func (*CompareAndSwapRequest) ProtoMessage()    {}
func (*CompareAndSwapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{2}
}

func (m *CompareAndSwapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareAndSwapRequest.Unmarshal(m, b)
}
func (m *CompareAndSwapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareAndSwapRequest.Marshal(b, m, deterministic)
}
func (m *CompareAndSwapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareAndSwapRequest.Merge(m, src)
}
func (m *CompareAndSwapRequest) XXX_Size() int {
	return xxx_messageInfo_CompareAndSwapRequest.Size(m)
}
func (m *CompareAndSwapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareAndSwapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompareAndSwapRequest proto.InternalMessageInfo

func (m *CompareAndSwapRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type DecrementRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Delta                int64    `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecrementRequest) Reset()         { *m = DecrementRequest{} }
func (m *DecrementRequest) String() string { return proto.CompactTextString(m) }
func (*DecrementRequest) ProtoMessage()    {}
func (*DecrementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{3}
}

func (m *DecrementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecrementRequest.Unmarshal(m, b)
}
func (m *DecrementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecrementRequest.Marshal(b, m, deterministic)
}
func (m *DecrementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecrementRequest.Merge(m, src)
}
func (m *DecrementRequest) XXX_Size() int {
	return xxx_messageInfo_DecrementRequest.Size(m)
}
func (m *DecrementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecrementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecrementRequest proto.InternalMessageInfo

func (m *DecrementRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DecrementRequest) GetDelta() int64 {
	if m != nil {
		return m.Delta
	}
	return 0
}

type IncrementRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Delta                int64    `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrementRequest) Reset()         { *m = IncrementRequest{} }
func (m *IncrementRequest) String() string { return proto.CompactTextString(m) }
func (*IncrementRequest) ProtoMessage()    {}
func (*IncrementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{4}
}

func (m *IncrementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrementRequest.Unmarshal(m, b)
}
func (m *IncrementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrementRequest.Marshal(b, m, deterministic)
}
func (m *IncrementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrementRequest.Merge(m, src)
}
func (m *IncrementRequest) XXX_Size() int {
	return xxx_messageInfo_IncrementRequest.Size(m)
}
func (m *IncrementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncrementRequest proto.InternalMessageInfo

func (m *IncrementRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *IncrementRequest) GetDelta() int64 {
	if m != nil {
		return m.Delta
	}
	return 0
}

type ReplaceRequest struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplaceRequest) Reset()         { *m = ReplaceRequest{} }
func (m *ReplaceRequest) String() string { return proto.CompactTextString(m) }
func (*ReplaceRequest) ProtoMessage()    {}
func (*ReplaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{5}
}

func (m *ReplaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceRequest.Unmarshal(m, b)
}
func (m *ReplaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceRequest.Marshal(b, m, deterministic)
}
func (m *ReplaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceRequest.Merge(m, src)
}
func (m *ReplaceRequest) XXX_Size() int {
	return xxx_messageInfo_ReplaceRequest.Size(m)
}
func (m *ReplaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceRequest proto.InternalMessageInfo

func (m *ReplaceRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type SetRequest struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{6}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type TouchRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Seconds              int32    `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TouchRequest) Reset()         { *m = TouchRequest{} }
func (m *TouchRequest) String() string { return proto.CompactTextString(m) }
func (*TouchRequest) ProtoMessage()    {}
func (*TouchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{7}
}

func (m *TouchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TouchRequest.Unmarshal(m, b)
}
func (m *TouchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TouchRequest.Marshal(b, m, deterministic)
}
func (m *TouchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TouchRequest.Merge(m, src)
}
func (m *TouchRequest) XXX_Size() int {
	return xxx_messageInfo_TouchRequest.Size(m)
}
func (m *TouchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TouchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TouchRequest proto.InternalMessageInfo

func (m *TouchRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TouchRequest) GetSeconds() int32 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

type DeleteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllRequest) Reset()         { *m = DeleteAllRequest{} }
func (m *DeleteAllRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllRequest) ProtoMessage()    {}
func (*DeleteAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{9}
}

func (m *DeleteAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllRequest.Unmarshal(m, b)
}
func (m *DeleteAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllRequest.Merge(m, src)
}
func (m *DeleteAllRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllRequest.Size(m)
}
func (m *DeleteAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllRequest proto.InternalMessageInfo

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{10}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetMultiRequest struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultiRequest) Reset()         { *m = GetMultiRequest{} }
func (m *GetMultiRequest) String() string { return proto.CompactTextString(m) }
func (*GetMultiRequest) ProtoMessage()    {}
func (*GetMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{11}
}

func (m *GetMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultiRequest.Unmarshal(m, b)
}
func (m *GetMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultiRequest.Marshal(b, m, deterministic)
}
func (m *GetMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultiRequest.Merge(m, src)
}
func (m *GetMultiRequest) XXX_Size() int {
	return xxx_messageInfo_GetMultiRequest.Size(m)
}
func (m *GetMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultiRequest proto.InternalMessageInfo

func (m *GetMultiRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type Reply struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_671b7d4d1004a799, []int{12}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Reply) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "definitions.Item")
	proto.RegisterType((*AddRequest)(nil), "definitions.AddRequest")
	proto.RegisterType((*CompareAndSwapRequest)(nil), "definitions.CompareAndSwapRequest")
	proto.RegisterType((*DecrementRequest)(nil), "definitions.DecrementRequest")
	proto.RegisterType((*IncrementRequest)(nil), "definitions.IncrementRequest")
	proto.RegisterType((*ReplaceRequest)(nil), "definitions.ReplaceRequest")
	proto.RegisterType((*SetRequest)(nil), "definitions.SetRequest")
	proto.RegisterType((*TouchRequest)(nil), "definitions.TouchRequest")
	proto.RegisterType((*DeleteRequest)(nil), "definitions.DeleteRequest")
	proto.RegisterType((*DeleteAllRequest)(nil), "definitions.DeleteAllRequest")
	proto.RegisterType((*GetRequest)(nil), "definitions.GetRequest")
	proto.RegisterType((*GetMultiRequest)(nil), "definitions.GetMultiRequest")
	proto.RegisterType((*Reply)(nil), "definitions.Reply")
}

func init() { proto.RegisterFile("grpc/definitions/definitions.proto", fileDescriptor_671b7d4d1004a799) }

var fileDescriptor_671b7d4d1004a799 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x61, 0x6f, 0xd3, 0x30,
	0x10, 0x86, 0x09, 0x69, 0x56, 0x7a, 0x1b, 0x63, 0x9c, 0x40, 0x84, 0x01, 0x53, 0xb1, 0x34, 0xd1,
	0x4f, 0x43, 0x5a, 0x27, 0x81, 0x26, 0x34, 0x51, 0x31, 0x51, 0x0d, 0x89, 0x2f, 0x2e, 0xfc, 0x00,
	0x13, 0x1f, 0x2c, 0x9a, 0x9b, 0x04, 0xc7, 0x05, 0xf6, 0xb3, 0xf8, 0x87, 0xc8, 0x4e, 0xbb, 0x26,
	0x69, 0x0d, 0x2a, 0xdf, 0x6c, 0xdf, 0xbd, 0x97, 0x7b, 0x5f, 0x3d, 0x0a, 0xb0, 0x6f, 0xba, 0x48,
	0x5e, 0x4a, 0xfa, 0x9a, 0x66, 0xa9, 0x49, 0xf3, 0xac, 0xac, 0x9f, 0x8f, 0x0a, 0x9d, 0x9b, 0x1c,
	0xb7, 0x6b, 0x4f, 0x2c, 0x83, 0xce, 0x85, 0xa1, 0x29, 0xee, 0x41, 0x78, 0x45, 0xd7, 0x71, 0xd0,
	0x0f, 0x06, 0x3d, 0x6e, 0x8f, 0xf8, 0x00, 0xa2, 0x1f, 0x42, 0xcd, 0x28, 0xbe, 0xdd, 0x0f, 0x06,
	0x3b, 0xbc, 0xba, 0xe0, 0x01, 0x80, 0x12, 0xa5, 0xf9, 0x5c, 0x48, 0x61, 0x28, 0x0e, 0xfb, 0xc1,
	0x20, 0xe2, 0xb5, 0x17, 0x5b, 0xa7, 0x5f, 0x45, 0xaa, 0x85, 0x1d, 0x1f, 0x77, 0xaa, 0xfa, 0xf2,
	0x85, 0x0d, 0x01, 0x46, 0x52, 0x72, 0xfa, 0x3e, 0xa3, 0xd2, 0xe0, 0x21, 0x74, 0x52, 0x43, 0x53,
	0xf7, 0xd9, 0xed, 0xe3, 0xfb, 0x47, 0xf5, 0x65, 0xed, 0x5a, 0xdc, 0x95, 0xd9, 0x19, 0x3c, 0x7c,
	0x97, 0x4f, 0x0b, 0xa1, 0x69, 0x94, 0xc9, 0xc9, 0x4f, 0x51, 0x6c, 0xa8, 0x3f, 0x85, 0xbd, 0x73,
	0x4a, 0x34, 0x4d, 0x29, 0x33, 0x0b, 0xe9, 0x5a, 0xc3, 0x92, 0x94, 0x11, 0xce, 0x70, 0xc8, 0xab,
	0x8b, 0xd5, 0x5e, 0x64, 0xff, 0xa9, 0x7d, 0x05, 0xbb, 0x9c, 0x0a, 0x25, 0x12, 0xda, 0x70, 0xe1,
	0x21, 0xc0, 0x84, 0xcc, 0xc6, 0x2e, 0x77, 0x3e, 0xe5, 0xb3, 0xe4, 0xd2, 0xbf, 0x65, 0x0c, 0xdd,
	0x92, 0x92, 0x3c, 0x93, 0xa5, 0xdb, 0x33, 0xe2, 0x8b, 0x2b, 0x7b, 0x0e, 0x77, 0xcf, 0x49, 0x91,
	0x21, 0xaf, 0x98, 0xa1, 0x0d, 0xd1, 0xb6, 0x8c, 0x94, 0x9a, 0x77, 0xb1, 0x03, 0x80, 0x31, 0xf9,
	0x63, 0x61, 0x87, 0x70, 0x6f, 0x4c, 0xe6, 0xe3, 0x4c, 0x99, 0x74, 0xd1, 0x84, 0xd0, 0xb9, 0xa2,
	0xeb, 0x32, 0x0e, 0xfa, 0xe1, 0xa0, 0xc7, 0xdd, 0x99, 0xbd, 0x87, 0xc8, 0xe6, 0xe4, 0x62, 0x24,
	0xad, 0x73, 0x3d, 0x9f, 0x51, 0x5d, 0xf0, 0x05, 0x44, 0xd6, 0xa0, 0x5d, 0x3a, 0x5c, 0x1f, 0x40,
	0x55, 0x3f, 0xfe, 0x1d, 0x41, 0x57, 0xea, 0x44, 0x24, 0x97, 0x84, 0x27, 0x10, 0x8e, 0xa4, 0xc4,
	0x47, 0x8d, 0xe6, 0x25, 0x7a, 0xfb, 0xd8, 0x28, 0xb8, 0xcf, 0xb3, 0x5b, 0xf8, 0x01, 0x76, 0x9b,
	0xa4, 0x21, 0x6b, 0xf4, 0xad, 0xc5, 0xd0, 0x33, 0xeb, 0x2d, 0xf4, 0x6e, 0xa8, 0xc3, 0x67, 0x8d,
	0x96, 0x36, 0x8d, 0xfe, 0x09, 0x37, 0xec, 0xb5, 0x26, 0xb4, 0x99, 0xf4, 0x4c, 0x78, 0x03, 0xdd,
	0x39, 0x81, 0xf8, 0x64, 0xa5, 0x61, 0xc9, 0xa5, 0x47, 0x7d, 0x02, 0xe1, 0x84, 0x4c, 0x2b, 0xc3,
	0x25, 0x98, 0x1e, 0xd5, 0x6b, 0x88, 0x1c, 0x87, 0xf8, 0xb8, 0x51, 0xae, 0xb3, 0xe9, 0x51, 0x9e,
	0xc2, 0x56, 0x85, 0x18, 0xee, 0xb7, 0xe2, 0xaa, 0xa1, 0xf9, 0xb7, 0xb4, 0xe7, 0x78, 0xae, 0xa4,
	0xdd, 0xc4, 0xd6, 0xef, 0x76, 0xbc, 0xe2, 0x76, 0xfc, 0x2f, 0xb7, 0x67, 0x70, 0x67, 0x81, 0x38,
	0x3e, 0x6d, 0x4b, 0xeb, 0xe4, 0xaf, 0xd7, 0x7f, 0xd9, 0x72, 0x3f, 0xe5, 0xe1, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xab, 0x00, 0xee, 0x72, 0xba, 0x05, 0x00, 0x00,
}
